### ISSUE TITLE
Minor error in `Shadow Depth`

### ISSUE THREAD

**Issue by JanCaha** [zoran-cuckovic/QGIS-terrain-shading#10]
If I run `Shadow Depth` algorithm I see an error: 

`TerrainShading\shading_algorithm.py", line 288, in postProcessAlgorithm path = path.dirname(__file__) + path AttributeError: 'str' object has no attribute 'dirname'`

Looking at the code at that line, there seems to be type a typo.

`path = path.dirname(__file__) + path` should probably be `path = os.dirname(__file__) + path`. 
 
It does not crash the algorithm and even the result is obtained fine, just the style is not applied.

**Comment by zoran-cuckovic** [comment]
Ah, what a basic error ! I'll wait for one more week, and publish a fixed version.
Thank you for reporting !

**Comment by JanCaha** [comment]
Just a minor problem. It happens to everyone. Otherwise the plugin is great ;-)
