### ISSUE TITLE
Integrate shadow height in R 

### ISSUE THREAD

**Issue by anarvaezv** [zoran-cuckovic/QGIS-terrain-shading#11]
HI Zoran, 
 I am trying to build a long routing and was oundering whether the algorithm Shadow height can be integrated in R and how ? 
Coudl you please help me ? 
And I am actuallz mor interested on whether there is shadow or not? the height itself is not that relevant for me ? do you have something doing just this ?

**Comment by zoran-cuckovic** [comment]
Hello, 
This QGIS plugin is coded in Python and it's not intended to function as a standalone module. This makes integration in R difficult. 
That being said, there is a very powerful module for 3D visualisation in R : [https://www.rayshader.com/](https://www.rayshader.com/ ). Have you checked it out already ? It can model shadows and much more.

**Comment by anarvaezv** [comment]
Dear Zoran-Cuckovic/Qgis-Terrain-Shading,
 thank you for fast answer. I have look in R and found a solution is nice
and simple I can share the code with you if you want to see.

Best Regards,

Alejandra
