### ISSUE TITLE
Failed to execute

### ISSUE THREAD

**Issue by luoyaya123** [zoran-cuckovic/QGIS-terrain-shading#16]
Only keep the default state of the parameters and execute it with your own Dem data, the following error will be reported.Raw data size [8658, 6471]
ValueError: could not broadcast input array from shape (6471,581) into shape (6471,580)
raise ValueError("array larger than output file, or offset off edge")
ValueError: array larger than output file, or offset off edge

**Comment by zoran-cuckovic** [comment]
Hello, 
This is a very basic error which shoudn't normally happen. Can you please provide more information on the module and parameters used ?

**Comment by luoyaya123** [comment]
The execution of the original error, no record is kept, only the execution history.
processing.run("terrain_shading:Hillshade (terrain shading)", {'INPUT':'E:/Projects/Project_gl30/Raw_Chuanyu/mosaic_chuanyu_dem/merge_chuanyu_180.tif','BIDIRECTIONAL':False,'DIRECTION':315,'ANGLE':45,'LAT_Z':2,'LON_Z':1,'DENOISE':1,'BYTE_FORMAT':False,'OUTPUT':'TEMPORARY_OUTPUT'})

Sorry, I don't know why the bug at the time was not reproduced, but a new bug occurred. The execution cannot get the result of a whole graph.
[data_result.docx](https://github.com/zoran-cuckovic/QGIS-terrain-shading/files/8362802/data_result.docx)
The Terrain Shading plugin in QGIS is used, version 0.9.4, module terrain_shading: Hillshade.

**Comment by zoran-cuckovic** [comment]
Hello,
It seems that only a fraction of the DEM was actually processed. This should be related to the lack of available disk space - did you check it ?
