### ISSUE TITLE
Error with texture shading DEM

### ISSUE THREAD

**Issue by mir123** [zoran-cuckovic/QGIS-terrain-shading#17]
Thanks for your amazing work! I'm having issues using texture shading on a DEM of Mexico at 120m resolution. You can find the data [here](https://www.inegi.org.mx/app/geo2/elevacionesmex/DownloadFile.do?file=CEM_V3_20170619_R120_Nacional.zip&res=120).

I have reprojected it with gdalwarp to EPSG:6369 - Mexico ITRF2008 / UTM zone 14N and then used the raster tools "Fill nodata cells" tool to replace nodata with zeros.

When trying to run texture shading with default options, I get the following errors:

```
Traceback (most recent call last):
File "/home/myuser/.local/share/QGIS/QGIS3/profiles/default/python/plugins/TerrainShading/modules/Raster.py", line 174, in add_to_buffer
view = self.buffer [y : y + y_off , x : x + x_off]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/myuser/.local/share/QGIS/QGIS3/profiles/default/python/plugins/TerrainShading/texture_algorithm.py", line 179, in processAlgorithm
dem.add_to_buffer(out[mx_view_out], gdal_put,
File "/home/myuser/.local/share/QGIS/QGIS3/profiles/default/python/plugins/TerrainShading/modules/Raster.py", line 183, in add_to_buffer
matrix += bd.ReadAsArray(*gdal_put)
TypeError: ufunc 'add' output (typecode 'O') could not be coerced to provided output parameter (typecode 'd') according to the casting rule ''same_kind''

Execution failed after 628.27 seconds (10 minutes 28 seconds)
```
I'm doing this on a Linux workstation with 32 GB RAM.

Any ideas?

**Comment by zoran-cuckovic** [comment]
Hello Mir, 
I've downloaded your data and I didn't have problems with the Terrain shading module. Did you succeed in the meanwhile ?

**Comment by mir123** [comment]
Thanks for testing! I haven't succeeded. When trying hillshading or ambient occlusion it finishes but only the first 25% of the DEM has been rendered (although the resulting layer extents cover the entire DEM). After about 30% progress (which takes about 25 minutes in my system) it starts going much faster, about one percent every two seconds. Max memory usage for the whole system all this time is about 9.5 GB, of which 3.6 are for QGIS. 

![image](https://user-images.githubusercontent.com/907400/171032242-f4826a18-5eae-440d-95cb-d05046ca9e7f.png)

This error shows up in the messages log:

`2022-05-30T11:29:08     WARNING    Hillshade : /tmp/processing_njnyGn/775aec350960462cbae988a5f613fd41/OUTPUT.tif, band 1: IReadBlock failed at X offset 0, Y offset 250: TIFFReadEncodedStrip() failed.`

**Comment by zoran-cuckovic** [comment]
Hello, 
This is so strange ! Do you have enough hard disk memory on your computer ? That's the only problem I can think of... 

Terrain shading is "single threaded", which means that it will use only one CPU core. If this is choking your computer, you can try to reduce the allocated buffer : 
![image](https://user-images.githubusercontent.com/6622934/171136688-e72d3cfe-cb1b-408b-8155-9cd24f5cf50f.png)

**Comment by mir123** [comment]
Same error in different workstation, but fixed it by actually increasing the buffer size to 5000. It now finished the job!

**Comment by zoran-cuckovic** [comment]
I'm glad that you've found a solution ! It's strange that you had to increase the buffer size, which forced all the data into memory (?).
