### ISSUE TITLE
Striping result when processing data in "shadow depth"

### ISSUE THREAD

**Issue by Archaeolithics** [zoran-cuckovic/QGIS-terrain-shading#19]
When processing data, a striping effect occurs upon running "shadow depth". The data is projected data of Europe. Tried it in EPSG 31468 and EPSG 25832.

Running QGIS 3.22.9 LTR

<img width="766" alt="image" src="https://user-images.githubusercontent.com/43182274/233018001-08f2c1ca-b4a8-418a-bb68-ed3d74baf63b.png">

**Comment by zoran-cuckovic** [comment]
Hello ! 
This is super strange ! I really cannot tell what's giong on - could you attach a sample of the data ?

**Comment by Archaeolithics** [comment]
Thanks for your quick reply. I really like your work!

I have created this file. Here the issue is happening. I also created a smaller cutout of this file which did not produce the issue. Up to now, I do not know why.

[test_50m_31468.zip](https://github.com/zoran-cuckovic/QGIS-terrain-shading/files/11272662/test_50m_31468.zip)

**Comment by zoran-cuckovic** [comment]
Hello !
There is a problem with your DEM. Nominally, the pixel size is 50m, but the actual size is 100 m (see the screenshot). This shouldn't be possible (!). The tools integrated in QGIS lack proper verification routines, so you may end up with just about anything.... 
You will have to recreate your DEM (perhaps you may repair this one by assigning proper pixel size, but I'm not sure about that)

![image](https://user-images.githubusercontent.com/6622934/233072159-2534fbd4-5a63-40b2-83be-b9b2bc96769f.png)

**Comment by Archaeolithics** [comment]
Okay, something is very wrong with this one. Thanks for the help. I'll keep you posted about this issue! Re-exporting did not work. But let's see what else...

**Comment by Archaeolithics** [comment]
I have re-created a dataset with proper sizing of the raster cells. Unfortunately, the issue remains:

<img width="730" alt="image" src="https://user-images.githubusercontent.com/43182274/233127484-fbb21a61-1f71-44ca-a34e-2b0d37b85166.png">

**Comment by Archaeolithics** [comment]
Moved the data to EPSG 3035 and ensured square pixels. not entirely sure which of both it was. But, it is working now. Thank you for your help. If I find out what the issue was, I'll keep you postet.
