### ISSUE TITLE
Shades extend without limit

### ISSUE THREAD

**Issue by juancobravo** [zoran-cuckovic/QGIS-terrain-shading#2]
Tried this on a USGS  ASTER Digital Elevation Model and regardless of the value I input on the 'angle' field, I get an output with shadows extending the whole width (or almost) of the raster file.

![Screen Shot 2019-03-13 at 9 05 04 AM](https://user-images.githubusercontent.com/48527015/54297654-8451ff80-4574-11e9-8020-17cd570846cb.png)

**Comment by zoran-cuckovic** [comment]
You must be working on unprojected data - it should be converted in a metric system.
This is how the algoithm calculates the vertical step to be added to each pixel in order to simulate light angle (line 190) : ` tilt = (sun_angle / 45)  * pixel_size`.
Now, pixel size in unprojected system is like 0,0001 **degrees**. So the tilt becomes near zero...

**Use projected data no matter the type of analysis.**

**Comment by juancobravo** [comment]
Thanks a lot for responding to my enquiry

Apologies if I’m taking too much  of your time with my newbie questions. Feel free to tell me you can’t help me beyond this point and I will continue trying to figure it out on my own.

As far as I can tell I am working on a projected data set.
With a pixel size of 0.0002777777777777777775,-0.0002777777777777777775
Here’s the full information from my dataset:

I’d appreciate if you’d let me know if I’m missing something, but like I said, no worries if you don’t have time to follow up on this

Thanks

JC


Information from provider
Name
ASTGTM2_N30W111_dem
Path
/Users/JCBravo/Documents/WN/MAPS/GIS/NORTEAMERICA/USGS ASTER DEM/ASTGTM2_N30W111_dem.tif <file:///Users/JCBravo/Documents/WN/MAPS/GIS/NORTEAMERICA/USGS%20ASTER%20DEM/ASTGTM2_N30W111_dem.tif>
CRS
EPSG:4326 - WGS 84 - Geographic
Extent
-111.0001388888888840,29.9998611111111089 : -109.9998611111111018,31.0001388888888876
Unit
degrees
Width
3601
Height
3601
Data type
Int16 - Sixteen bit signed integer
GDAL Driver Description
GTiff
GDAL Driver Metadata
GeoTIFF
Dataset Description
/Users/JCBravo/Documents/WN/MAPS/GIS/NORTEAMERICA/USGS ASTER DEM/ASTGTM2_N30W111_dem.tif
Compression
Band 1
STATISTICS_APPROXIMATE=YES
STATISTICS_MAXIMUM=2430
STATISTICS_MEAN=1176.8605442022
STATISTICS_MINIMUM=637
STATISTICS_STDDEV=263.34830204941
STATISTICS_VALID_PERCENT=100
More information
AREA_OR_POINT=Area
TIFFTAG_DATETIME=2011:03:15 21:26:05
TIFFTAG_DOCUMENTNAME=created at
TIFFTAG_IMAGEDESCRIPTION=SILC TIFF
TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
TIFFTAG_SOFTWARE=IDL 7.1.1, ITT Visual Information Solutions
TIFFTAG_XRESOLUTION=100
TIFFTAG_YRESOLUTION=100
Dimensions
X: 3601 Y: 3601 Bands: 1
Origin
-111,31.0001
Pixel Size
0.0002777777777777777775,-0.0002777777777777777775

**Comment by zoran-cuckovic** [comment]
Hi!
The info states, among other things: `Unit degrees`. But unit of what? - the elevation data is in meters, right? And then it says `Pixel Size 0.0002777777777777777775,-0.0002777777777777777775`. Can your pixel measure less than **one millimetre**?

The data you are using is organised in a latitude/longitude grid - which means it is not projected to a flat surface. You need to (re-)project your data in a metric coordinate system. Please see more on [projections in gis](https://www.google.com/search?q=gis+projections+explained).
