### ISSUE TITLE
90°, 180° and 270° do not work

### ISSUE THREAD

**Issue by pfefferCode** [zoran-cuckovic/QGIS-terrain-shading#20]
Hi!

thank you for this great Plug-In!

Unfortunately it does not work with the sun azimuth in 90°, 180° or 270° with the following data. It works with 91°, 181° and 271°.

I used this elevation data: https://www.wcs.nrw.de/geobasis/wcs_nw_dom?REQUEST=GetCoverage&SERVICE=WCS&VERSION=2.0.1&COVERAGEID=nw_dom&FORMAT=image/tiff&SUBSET=x(356000,357000)&SUBSET=y(5699000,5700000)&OUTFILE=dom1_32_356_5699_1_nw_2020&APP=timonline

(and the according Orthophoto: https://www.wcs.nrw.de/geobasis/wcs_nw_dop?REQUEST=GetCoverage&SERVICE=WCS&VERSION=2.0.1&COVERAGEID=nw_dop&FORMAT=image/tiff&SUBSET=x(356000,357000)&SUBSET=y(5699000,5700000)&RANGESUBSET=1,2,3&OUTFILE=dop10rgb_32_356_5699_1_nw_2022&APP=timonline )

The result using a sun azimuth of 90° will be an empty new layer.

Best regards,
   PfefferCode.

**Comment by zoran-cuckovic** [comment]
Yes, I confirm the bug - I will take a closer look at this issue. 
Thanks for providing the data for the test !

**Comment by zoran-cuckovic** [comment]
Resolved in version 0.9.5 (pending approval)

**Comment by pfefferCode** [comment]
In order to test, I need to wait, till the updated plug-in becomes available in QGis, correct?

**Comment by zoran-cuckovic** [comment]
Yes, the validation process can take up to several weeks. You can also download the unapproved version from https://plugins.qgis.org/plugins/ViewshedAnalysis/#plugin-versions and replace the existing plugin folder with the new one.
