### ISSUE TITLE
Would shadow depth work on the Moon

### ISSUE THREAD

**Issue by Gronk95** [zoran-cuckovic/QGIS-terrain-shading#22]
This is more of a question.

I'm trying to do a shading analysis for DEMs covering the South Pole of the Moon. Does the shadow depth algorithm work on the Moon? How would you interpret the output?

**Comment by zoran-cuckovic** [comment]
Hello Gronk, 
If you have good equipment, it should work on Moon as well ;) 
More seriously, there are no issues that I can think of, provided that you have a raster DEM. I guess that Moon data is in Lat/Lon format, which shouldn't pose problems (although projected data is preferred). I've already toyed with Mars DEM : no issues.
