### ISSUE TITLE
Almost no shadows no matter what I try for angle and radius

### ISSUE THREAD

**Issue by kannes** [zoran-cuckovic/QGIS-terrain-shading#3]
http://daten-hamburg.de/geographie_geologie_geobasisdaten/Digitales_Hoehenmodell/DGM10/DGM10_2x2KM_XYZ_HH_2016-01-04.zip is elevation data in UTM coordinates and meters for the heights.

License: Datenlizenz Deutschland Namensnennung 2, Freie und Hansestadt Hamburg, Landesbetrieb Geoinformation und Vermessung, 2014

Here it is as TIF: https://transfer.sh/xn2dQ/DGM10_25832.tif

In QGIS:

![image](https://user-images.githubusercontent.com/7661092/60769796-620c6080-a0d4-11e9-8aba-c14901fc3009.png)

Result with default settings:

![image](https://user-images.githubusercontent.com/7661092/60769801-69cc0500-a0d4-11e9-88c6-7b51cf1fa27e.png)

What ever I try, I only get hints of shadows "in" the data with some noticable shadows on its edges.

**Comment by zoran-cuckovic** [comment]
Hi!
I think you might be getting the correct result, actually. What is the depth (value) of your shadows on the edges of the elevation model, and inside it?

**Comment by zoran-cuckovic** [comment]
I'm closing this... If a DEM is surrounded by NoData, as in this case, then you might get very deep shadows on the edges.

**Comment by kannes** [comment]
I don't understand this, "no data" means there is nothing for shadows to be cast upon. I expected height differences within my DEM to cast shadows.

**Comment by zoran-cuckovic** [comment]
Data in raster files is (normally) numerical : the code for "nothing" has to be a number. Zero is problematic for elevations, so usually we choose an arbitrary number (e.g. -9999). Thus, you will end up with vertical drops of 10 km, or more!

The script I made does not handle NoData - I propose to develop an updated version which will be able to deal with this problem (see on [Kickstarter](https://www.kickstarter.com/projects/archaeology/terrain-shading-plugin-for-qgis)). 

see also: https://gis.stackexchange.com/questions/158503/9999-no-data-value-becomes-0-when-writing-array-to-gdal-memory-file

**Comment by kannes** [comment]
You can use masked arrays https://docs.scipy.org/doc/numpy/reference/generated/numpy.ma.masked_where.html or maybe replacing them with np.nan would fit (less memory usage I'd think).

Good luck on the Kickstarter! :)
