### ISSUE TITLE
error loading .qml style file

### ISSUE THREAD

**Issue by bellanz80** [zoran-cuckovic/QGIS-terrain-shading#4]
Hi, I'm testing the plug, but I get an error loading the .qml style files. All 3 files return the same error: line 45 ... can you help me? Thank you!

![Image 1](https://user-images.githubusercontent.com/38449926/71916146-e81c6900-3142-11ea-9f71-e6115ac03a1d.png)

![Image 2](https://user-images.githubusercontent.com/38449926/71916155-ece11d00-3142-11ea-8bb9-2efd27fdfb9a.png)

**Comment by zoran-cuckovic** [comment]
Ahem... I don't have a clue... You have a problem with XML reader, but the .qml style file shouldn't pose problems.
You will have to make the style by hand, I'm afraid (which takes no more than a couple of minutes). Thanks for reporting the issue!

**Comment by bellanz80** [comment]
Thank's!
