### ISSUE TITLE
Terrain Shading plugin does not appear at 3.14.1

### ISSUE THREAD

**Issue by stuskier** [zoran-cuckovic/QGIS-terrain-shading#6]
At 3.14.1, I added Terrain Shading via Manage and Install Plugins dropdown.  The plugin installed (I can see it in c:\users...\plugins\TerrainShading) but it does not appear in the Processing Toolbox, as shown below.  Manually installing via GitHub download results in same problem.

Why can't I see Processing Toolbox > Raster terrain analysis > Natural Shading?  Thanks.

![Capture](https://user-images.githubusercontent.com/12805900/88433355-bef7b900-cdb2-11ea-9fcc-0cd4b7c19489.PNG)

**Comment by zoran-cuckovic** [comment]
Hello!
What you see here are native QGIS plugins (thus the green Q logo). Terrain Shading is a separate (external) provider: see figure.

![image](https://user-images.githubusercontent.com/6622934/88460317-a31c1200-ce9b-11ea-8c0e-09bfa71d5c47.png)

**Comment by stuskier** [comment]
Thanks for the quick reply!
 
You are correct, I now see the Terrain Shading tool.
 
May I suggest that you update your install instructions to show where to find the tool? 
 
Best regards,
 
Stu
 
 
-----Original Message-----
