### ISSUE TITLE
Plug-in not working in Python script for loop: "Parameter value is incorrect"

### ISSUE THREAD

**Issue by jlenh** [zoran-cuckovic/QGIS-terrain-shading#8]
Hello,
I am using the plug-in function "Shadow depth" in a Python script inside QGIS (3.10.7).
I want to loop through different direction and elevation values on the same raster input. However the functions seems to run only when I write directly the parameter values in the processing.run command instead of accessing them through a list. I have tried several alternatives about how to add the parameter dict in the function but it never seems to work.
I have added below an extract of the code I am trying to run.
Do you know what could cause this or if it is coming from QGIS instead of the plug-in?
Thanks!

```
angles_azimuth = np.arange(0, 360, 20, dtype=int)
angles_elevation = np.arange(0, 70, 5, dtype=int)
input_file = '/path/to/input.tif'
path_output = '/path/to/output_dir/'
dict_param = dict.fromkeys(['INPUT', 'DIRECTION', 'ANGLE', 'SMOOTH', 'OUTPUT'])
dict_param['INPUT'] = input_file
dict_param['SMOOTH'] = False

for i in range(len(angles_azimuth)):
    for j in range(len(angles_elevation)):
       azi = angles_azimuth[i]
       ele = angles_elevation[j]     
       dict_param['DIRECTION'] = azi
       dict_param['ANGLE'] = ele
       dict_param['OUTPUT'] = path_output + 'TERRAIN_SHADOW_'+str(azi)+'_'+str(ele)+'.tif'
       print(dict_param)
       processing.run("DEM shading:Shadow depth", dict_param)
```

Error:

> {'INPUT': '/Users/.../MERGED.tif', 'DIRECTION': 50, 'ANGLE': 0, 'SMOOTH': False, 'OUTPUT': '/Users/TERRAIN_SHADOW_50_0.tif'}
Traceback (most recent call last):
  File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 53, in <module>
  File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/plugins/processing/tools/general.py", line 106, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
  File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/plugins/processing/core/Processing.py", line 137, in runAlgorithm
    raise QgsProcessingException(msg)
_core.QgsProcessingException: Incapable d’exécuter l’algorithme
La valeur du paramètre DIRECTION est incorrecte.

Code that works but no for loop:
```
processing.run("DEM shading:Shadow depth", {'INPUT': input_file,
    'DIRECTION': 50, 'ANGLE': 0, 'SMOOTH': False,
    'OUTPUT': output_file})
```

**Comment by zoran-cuckovic** [comment]
Hello, 
If it works when hard coded, then the problem should be you dictionary format. It all seems fine to me :  perhaps you could try casting the direction parameter to integer (I use integers in the algo). 
`dict_param['DIRECTION'] = int(azi)` 


PS, angle 0 will give you an unrealistic result.

**Comment by jlenh** [comment]
That seemed to do the trick, thanks!
The numpy array gives elements of type int64 which seem not be supported as input of the function.
