### ISSUE TITLE
Data should be projected in a metric system (continuation)

### ISSUE THREAD

**Issue by francis33** [zoran-cuckovic/QGIS-terrain-shading#9]
Hi,

By mistake, I closed the subject. That's why I send a new post on the same topic.

Talking about projection systems, you aswered me yesterday :

Hello,
WGS84 is not a true geographic projection : see my blog post . Your data is in degrees, not in metres

Thanks a lot for your quick reply.
I learn a lot with your blog. Following that, I read a lot of articles concerning projection systems.
I used the projection system "EPSG:3857 - WGS 84 / Pseudo-Mercator - Projeté".
My data are now in meters and the plugin worked. But i had the message :

*** ERROR!
Raster pixels are irregular in shape (probably due to incorrect projection)!

Having a look to the ouput file, I noticed a sort of 'grid' in the visual result (see attached file named "grid").
Is the choice of "EPSG:3857 - WGS 84 / Pseudo-Mercator - Projeté" a bad choice ?
Is this "bad" result linked to the error message ?

Is a UTM projection system a best choice ?
(I work on north american areas, including canada. I'm studying global relief)
Thanks a lot for your help.
Francis
![Ambiant Occlusion](https://user-images.githubusercontent.com/53442186/89665429-fdc05f80-d8d8-11ea-8454-e2d55c82cd24.jpg)
![grid](https://user-images.githubusercontent.com/53442186/89665438-02851380-d8d9-11ea-8ce3-fcae4d12d203.jpg)

**Comment by Coastal0** [comment]
I've also had this error message, and I'm using a projected grid (definitely in meters). Would be good to find a solution.

**Comment by zoran-cuckovic** [comment]
Hello !
Web mercator is not the ideal solution - unless you work on a continent wide scale. However, it does give a model in meters, which can be processed without a problem. 

Your problem is due to distortions between angular and metric units. You should experiment with resampling/interpolation options (in the reprojection module). Bilinear interpolation usually works fine.
